### PR TITLE
Add install instructions for dependencies in README

### PR DESCRIPTION
**Pull request by digaru19**
Added install instructions for dependencies in Ubuntu-based and Fedora-based distributions.

### CODE REVIEW

**Comment by achilleas-k** [comment]
We're eventually (as soon as we get a proper release) put this on pypi, so I think instead of having git instructions at the top, it would be nicer to mention that the easiest way to install it is with `pip install`.

But first it should mention that in order to `pip install odml-ui`, you first need to apt-get/yum install the dependencies.

**Comment by digaru19** [comment]
@achilleas-k  Yeah sure .. I'll make the changes :+1: ..  So, should this PR (with the newer `pip install` instructions) be on hold until we make a release ?

**Comment by achilleas-k** [comment]
Perhaps that's a good idea,  yeah. We wouldn't want the front-facing README to have instructions mentioning `pip install` and not have it working.

**Comment by achilleas-k** [comment]
Hey, @digaru19. What's the status of this?

**Pull request merged**
