### PR TITLE
Add Drop-Down menu for Property data types

### PR DESCRIPTION
**Pull request by digaru19**

### CODE REVIEW

**Comment by jgrewe** [comment]
very nice! 
could you add that there is an error message, when the conversion failed. E.g. when the user changes the dtype from string to int and the conversion fails it so far just throws an exception on the command line but the user receives no feedback

**Comment by achilleas-k** [comment]
We could give some thought to the default values for each type. While simply switching around different types, I ended up with a text field with value `None` which I then couldn't switch to `bool` because it wouldn't convert.

An error message, as @jgrewe mentioned would be nice, but also we could perhaps make sure that if the user is cycling through (or randomly picking) dtypes, when no value is already set, it doesn't result in a state where conversions aren't possible.

**Comment by jgrewe** [comment]
a very good point... and a trap that can be really annoying

**Comment by digaru19** [comment]
Forgot to commit the **error message** changes to the repo. :sweat_smile: 

Yeah, some default value for each data-type is a good idea. I had a doubt in this regard, what does a property without a value signify ? If it does not specify anything meaningful, then we should have a default value for a particular type. It will also help them in knowing the format of the data that they need to edit, for example for _datetime_, it's good to know the format string which is being expected from the user.

**Comment by achilleas-k** [comment]
> for example for datetime, it's good to know the format string which is being expected from the user

Than's a good point. I agree. Perhaps it should default to the current date?

**Comment by digaru19** [comment]
Alright, so, if we are planning to have default values for the types, how does this look ..
- **string** - `" "`
- **text** - `" "`
- **int** - `0`
- **float** - `0.0`
- **url** - `" "`
- **datetime** - `current date and time`
- **date** - `current date`
- **time** - `current time`
- **boolean** - `True`
- **person** - (no idea)
- **boolean** - (no idea)

We can have the `value` default to the above values in the odML library, whenever a new one is created. 
Regarding the conversion of odML types, I was thinking of modelling these types as a **directed graph**, where these types represent a node in the graph. Outgoing edges from a node indicate that a conversion is possible, and we can then have **custom type converters**, associated with each edge. Or, if the conversion is not possible (no edge), then the value gets the default value of the new type. 
It is just an abstract idea. What do you guys think ? 
We can implement this later, in case we are short of time.

**Comment by achilleas-k** [comment]
Text type fields (string, text, url) should probably be empty string `""` instead of space `" "`.
Boolean should default to `false`.

I like the idea of specifying conversion paths and using the default when not possible. For example, the following make sense to me:
- Switching a property from `int 42` to `float` converts the value to `42.0`.
- Switching a property from `URL "https://example.com"` to `string` keeps the value as is.
- Switching a property from `float 4.2` to `int` floors the value to `4`.
- Switching a property from `string "foo"` to `float` defaults to `0.0`.

There's obviously data loss in those last two examples, but I think that's acceptable given this is a GUI with an undo function. Perhaps in the case of data loss, we can display a warning, a non-modal message under the toolbar so as to not interrupt the user, so that the user notices that an existing value was discarded.

**Comment by achilleas-k** [comment]
Merging this. Conversion can be discussed and solved in an upcoming PR.

**Pull request merged**
